# Generated by Django 3.2.16 on 2022-12-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0006_librodigital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librodigital',
            name='autor',
        ),
    ]
