# Generated by Django 3.2.16 on 2022-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0007_remove_librodigital_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librodigital',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
